---
# tasks file for App
- name: Create springboot service
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: '{{ ansible_operator_meta.name }}'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
       type: NodePort
       selector:
         app: '{{ ansible_operator_meta.name }}'
       ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
- name: Create Springboot deployment
  community.kubernetes.k8s:
    definition:
       apiVersion: apps/v1
       kind: Deployment
       metadata:
         name: '{{ ansible_operator_meta.name }}'
         namespace: '{{ ansible_operator_meta.namespace }}'
         labels:
           app: '{{ ansible_operator_meta.name }}'
       spec:
         replicas: "{{size}}"
         selector:
           matchLabels:
              app: '{{ ansible_operator_meta.name }}'
         template:
            metadata:
               labels:
                  app: '{{ ansible_operator_meta.name }}'
            spec:
             containers:
              - name: '{{ ansible_operator_meta.name }}'
                image: "docker.io/krishnakant002/spring-mongo-service:2.0"
                env:
                 - name: MONGO_HOST
                   valueFrom:
                     configMapKeyRef:
                      name: '{{ ansible_operator_meta.name }}'
                      key: host
                 - name: MONGO_USERNAME 
                   valueFrom:
                    secretKeyRef:
                     name: '{{ ansible_operator_meta.name }}'
                     key: root-username
                 - name: MONGO_PASSWORD 
                   valueFrom:
                    secretKeyRef:
                     name: '{{ ansible_operator_meta.name }}'
                     key: root-password   
                 - name: MONGO_DB
                   valueFrom:
                    configMapKeyRef:
                     name: '{{ ansible_operator_meta.name }}'
                     key: database    
                ports:
                - containerPort: 8080
